window.HOME_DEMO_EVENTS = [
  {
    id: -1,
    is_demo: true,
    organizador_id: 0,
    organizador_nome: 'EventoCom Demo',
    nome: 'Festival Verão Sonoro 2025',
    descricao: 'O Festival Verão Sonoro reúne mais de 20 atrações musicais em um único dia, com palcos simultâneos, área gastronômica e espaço cultural.',
    categoria: 'Música',
    data_inicio: '2025-07-12',
    hora_inicio: '16:00',
    hora_fim: '23:00',
    formato: 'presencial',
    entrada: 'pago',
    entrada_label: 'Pago – R$ 40,00',
    local_nome: 'Parque Municipal',
    cidade: 'São Paulo',
    estado: 'SP',
    idade: 'Livre',
    imagem_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80'
  },
  {
    id: -2,
    is_demo: true,
    organizador_id: 0,
    organizador_nome: 'EventoCom Demo',
    nome: 'Sabores da Cidade - Edição Especial',
    descricao: 'Uma feira gastronômica com mais de 50 expositores trazendo culinária local e internacional.',
    categoria: 'Gastronomia',
    data_inicio: '2025-07-19',
    hora_inicio: '11:00',
    hora_fim: '20:00',
    formato: 'presencial',
    entrada: 'gratuito',
    entrada_label: 'Gratuito',
    local_nome: 'Praça Central',
    cidade: 'Belo Horizonte',
    estado: 'MG',
    idade: 'Livre',
    imagem_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80'
  },
  {
    id: -3,
    is_demo: true,
    organizador_id: 0,
    organizador_nome: 'EventoCom Demo',
    nome: 'Corrida Solidária 5K & 10K',
    descricao: 'Participe da corrida que une saúde e solidariedade com categorias 5K e 10K.',
    categoria: 'Esportes',
    data_inicio: '2025-07-26',
    hora_inicio: '07:00',
    hora_fim: '12:00',
    formato: 'presencial',
    entrada: 'pago',
    entrada_label: 'Pago - R$ 25,00 (renda para ONG local)',
    local_nome: 'Aterro do Flamengo',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    idade: '+12',
    imagem_url: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=800&q=80'
  },
  {
    id: -4,
    is_demo: true,
    organizador_id: 0,
    organizador_nome: 'EventoCom Demo',
    nome: 'Exposição Coletiva: Cores da Comunidade',
    descricao: 'Uma exposição de artes visuais que reúne 30 artistas locais em torno do tema comunidade e pertencimento.',
    categoria: 'Arte & Cultura',
    data_inicio: '2025-08-05',
    hora_inicio: '10:00',
    hora_fim: '18:00',
    formato: 'presencial',
    entrada: 'gratuito',
    entrada_label: 'Gratuito',
    local_nome: 'Centro Cultural',
    cidade: 'Curitiba',
    estado: 'PR',
    idade: 'Livre',
    imagem_url: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?w=800&q=80'
  },
  {
    id: -5,
    is_demo: true,
    organizador_id: 0,
    organizador_nome: 'EventoCom Demo',
    nome: 'Hackathon Comunidade Tech 2025',
    descricao: 'Desafios de programação, design e inovação para resolver problemas reais da comunidade.',
    categoria: 'Tecnologia',
    data_inicio: '2025-08-09',
    hora_inicio: '08:00',
    hora_fim: '22:00',
    formato: 'presencial',
    entrada: 'gratuito',
    entrada_label: 'Gratuito (inscrição obrigatória)',
    local_nome: 'Hub de Inovação',
    cidade: 'Recife',
    estado: 'PE',
    idade: '+16',
    imagem_url: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&q=80'
  },
  {
    id: -6,
    is_demo: true,
    organizador_id: 0,
    organizador_nome: 'EventoCom Demo',
    nome: 'Dia de Bem-Estar: Yoga & Meditação no Parque',
    descricao: 'Uma manhã ao ar livre dedicada ao equilíbrio físico e mental com yoga e meditação guiada.',
    categoria: 'Saúde & Bem-estar',
    data_inicio: '2025-08-16',
    hora_inicio: '06:30',
    hora_fim: '10:00',
    formato: 'presencial',
    entrada: 'gratuito',
    entrada_label: 'Gratuito',
    local_nome: 'Parque da Cidade',
    cidade: 'Brasília',
    estado: 'DF',
    idade: 'Livre',
    imagem_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80'
  }
];
